Repository prgrms-web-devcourse/Team-12-ReviewRanger-FE, pull requests merged in 2023-10, with the labels that each got.

#4 REV-32/초기 세팅 작업 진행
  .eslintrc.cjs
  .github/pull_request_template.md
  .github/workflows/devserver_delpoy.yml
  .gitignore
  .husky/commit-msg
  .prettierrc
  commitlint.config.cjs
  index.html
  package-lock.json
  package.json
  postcss.config.js
  src/App.tsx
  src/apis/apiClient.ts
  src/apis/index.ts
  src/components/index.ts
  src/constants/index.ts
  src/hooks/index.ts
  src/index.css
  src/main.tsx
  src/mock/index.ts
  src/pages/index.ts
  src/services/index.ts
  src/types/index.ts
  src/utils/index.ts
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 세팅

#5 REV-64/초기 세팅 작업 진행
  .eslintrc.cjs
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/apis/hooks/index.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/test.ts
  src/mocks/index.ts
  src/mocks/worker.ts
  src/services/index.ts
  tailwind.config.js
Labels: 세팅

#7 REV-67/검색 input 컴포넌트 구현
  src/assets/icons/index.ts
  src/assets/icons/search.svg
  src/components/SearchBar/index.tsx
  src/components/index.ts
Labels: 기능

#8 REV-70/아이콘 버튼 컴포넌트 구현
  src/assets/icons/index.ts
  src/assets/icons/table_send.svg
  src/components/IconButton/IconButton.tsx
  src/components/IconButton/index.ts
  src/components/index.ts
Labels: 스타일, 기능

#11 REV-71/별점 컴포넌트 구현
  src/assets/icons/index.ts
  src/assets/icons/star.svg
  src/components/StarRating/StarRatingItem.tsx
  src/components/StarRating/StarRatingList.tsx
  src/components/StarRating/index.ts
  src/components/index.ts
  src/hooks/useStarRate/constants.ts
  src/hooks/useStarRate/useStarRate.ts
Labels: 기능

#13 REV-76/비밀번호 입력 컴포넌트 구현
  src/assets/icons/index.ts
  src/assets/icons/password.svg
  src/assets/icons/passwordconfirm.svg
  src/components/PasswordInput.tsx
  src/components/index.ts
Labels: 기능

#9 REV-69/개별 답변 컴포넌트 구현
  src/assets/icons/index.ts
  src/components/PersonalAnswer/index.tsx
  src/components/Profile/index.tsx
  src/components/index.ts
Labels: 기능

#15 REV-77/유저 리스트 박스 컴포넌트
  src/components/Profile/index.tsx
  src/components/UserList/index.tsx
  src/components/index.ts
Labels: 기능

#10 REV-75/설명 컴포넌트 구현
  src/components/PageIntro/index.tsx
  src/components/index.ts
Labels: 스타일, 기능

#12 REV-73/질문 형식 컴포넌트 구현
  src/assets/icons/index.ts
  src/assets/icons/menu.svg
  src/components/QuestionItem/index.tsx
  src/components/index.ts
  tailwind.config.js
Labels: 기능

#14 REV-74/리뷰 리스트 컴포넌트 구현
  src/components/ReviewList/index.tsx
  src/components/index.ts
  src/types/index.ts
  src/types/reviews.ts
Labels: 기능
