Repository prgrms-web-devcourse/Team-12-ReviewRanger-FE, pull requests merged in 2023-11, with the labels that each got.

#17 REV-93/page,component 파일 세팅
  src/components/Header/index.tsx
  src/components/PassWordInput/index.tsx
  src/components/index.ts
  src/pages/CreatedReviewManagePage/components/index.ts
  src/pages/CreatedReviewManagePage/index.tsx
  src/pages/LandingPage/components/index.ts
  src/pages/LandingPage/index.tsx
  src/pages/LoginPage/components/index.ts
  src/pages/LoginPage/index.tsx
  src/pages/MainPage/components/CreatedReviewItem/index.tsx
  src/pages/MainPage/components/InvitedReviewItem/index.tsx
  src/pages/MainPage/components/ReceivedReviewItem/index.tsx
  src/pages/MainPage/components/index.ts
  src/pages/MainPage/index.tsx
  src/pages/MyPage/components/ImageUpload/index.tsx
  src/pages/MyPage/components/index.ts
  src/pages/MyPage/index.tsx
  src/pages/ReviewCreatePage/components/ReviewTypeModal/index.tsx
  src/pages/ReviewCreatePage/components/UserList/index.tsx
  src/pages/ReviewCreatePage/components/index.ts
  src/pages/ReviewCreatePage/index.tsx
  src/pages/ReviewReplyPage/components/ReplyDropDown/index.tsx
  src/pages/ReviewReplyPage/components/ReplyHexagon/index.tsx
  src/pages/ReviewReplyPage/components/index.ts
  src/pages/ReviewReplyPage/index.tsx
  src/pages/ReviewResultPage/index.tsx
  src/pages/SignUpPage/index.tsx
  src/pages/index.ts
Labels: 세팅

#16 REV-91/dayjs 세팅
  package-lock.json
  package.json
  src/components/UserList/index.tsx
Labels: 리팩토링, 세팅

#18 REV-92/아이콘 컴포넌트 세팅
  src/assets/icons/arrow-below.svg
  src/assets/icons/arrow-left.svg
  src/assets/icons/basic-profile.svg
  src/assets/icons/check-in-the-circle.svg
  src/assets/icons/check.svg
  src/assets/icons/close-in-the-circle.svg
  src/assets/icons/close.svg
  src/assets/icons/eye-off.svg
  src/assets/icons/eye-on.svg
  src/assets/icons/filter.svg
  src/assets/icons/index.ts
  src/assets/icons/menu.svg
  src/assets/icons/password.svg
  src/assets/icons/passwordconfirm.svg
  src/assets/icons/preview.svg
  src/assets/icons/registration.svg
  src/assets/icons/search.svg
  src/assets/icons/send.svg
  src/assets/icons/text.svg
Labels: 기능

#19 REV-134/비밀번호 입력 컴포넌트 수정
  src/assets/icons/eye-off.svg
  src/assets/icons/eye-on.svg
  src/components/PasswordInput/index.tsx
Labels: 리팩토링

#20 REV-94/router 세팅
  src/App.tsx
  src/routes/Layout.tsx
  src/routes/constants.ts
  src/routes/index.ts
  src/routes/router.tsx
  tailwind.config.js
Labels: 스타일, 세팅

#21 REV-96/mock API (메인) 구현
  .husky/commit-msg
  src/apis/hooks/index.ts
  src/apis/hooks/useEditResponse.ts
  src/apis/hooks/useGetCreatedReview.ts
  src/apis/hooks/useGetInvitedReview.ts
  src/apis/hooks/useGetReceivedReview.ts
  src/apis/hooks/useGetResponseForm.ts
  src/apis/hooks/useGetReviewResult.ts
  src/mocks/handlers/dummyData.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/main.ts
  src/mocks/worker.ts
Labels: 기능

#22 REV-98/mock API (회원가입) 구현
  src/apis/hooks/index.ts
  src/apis/hooks/useCheckDuplicatedEmail.ts
  src/apis/hooks/useCheckDuplicatedName.ts
  src/apis/hooks/useSignUp.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/signUp.ts
  src/mocks/worker.ts
  src/pages/SignUpPage/index.tsx
Labels: 기능

#23 REV-99/mock API (로그인) 구현
  .husky/commit-msg
  src/apis/hooks/index.ts
  src/apis/hooks/useLogin.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/login.ts
  src/mocks/worker.ts
  src/pages/LoginPage/index.tsx
Labels: 기능

#25 REV-100/mock API (마이페이지) 구현
  src/apis/hooks/index.ts
  src/apis/hooks/useEditProfile.ts
  src/apis/hooks/useLogout.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/profile.ts
  src/mocks/worker.ts
  src/pages/MyPage/index.tsx
Labels: 기능

#26 REV-101/mock API (설문 생성) 구현
  src/apis/hooks/index.ts
  src/apis/hooks/useCreateSurvey.ts
  src/apis/hooks/useGetAllUser.ts
  src/mocks/handlers/create.ts
  src/mocks/handlers/dummyData.ts
  src/mocks/handlers/index.ts
  src/mocks/worker.ts
  src/pages/ReviewCreatePage/index.tsx
Labels: 기능

#27 REV-102/mock API (답변 유형) 구현
  src/apis/hooks/index.ts
  src/apis/hooks/useCreateResponse.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/main.ts
  src/mocks/handlers/response.ts
  src/mocks/worker.ts
  src/pages/ReviewReplyPage/index.tsx
Labels: 기능

#24 REV-97/mock API (생성한 리뷰 관리) 구현
  src/apis/hooks/index.ts
  src/apis/hooks/useCloseSurvey.ts
  src/apis/hooks/useDeleteSurvey.ts
  src/apis/hooks/useGetAuthorResponsesQuery.ts
  src/apis/hooks/useGetRecipientResponsesQuery.ts
  src/apis/hooks/useGetSingleAuthorResponse.ts
  src/apis/hooks/useGetSingleRecipientResponse.ts
  src/apis/hooks/useSendReview.ts
  src/apis/index.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/manageHandler/index.ts
  src/mocks/handlers/manageHandler/mockData/index.ts
  src/mocks/handlers/test.ts
  src/mocks/worker.ts
  src/pages/CreatedReviewManagePage/index.tsx
Labels: 기능

#29 REV-143/tailwind 세팅
  tailwind.config.js
Labels: 세팅

#28 REV-141/api 제네릭 타입 추가
  src/apis/hooks/useCheckDuplicatedEmail.ts
  src/apis/hooks/useCheckDuplicatedName.ts
  src/apis/hooks/useCreateSurvey.ts
  src/apis/hooks/useEditProfile.ts
  src/apis/hooks/useEditResponse.ts
  src/apis/hooks/useGetAllUser.ts
  src/apis/hooks/useGetCreatedReview.ts
  src/apis/hooks/useGetInvitedReview.ts
  src/apis/hooks/useGetReceivedReview.ts
  src/apis/hooks/useGetResponseForm.ts
  src/apis/hooks/useGetReviewResult.ts
  src/apis/hooks/useLogin.ts
  src/apis/hooks/useLogout.ts
  src/apis/hooks/useSignUp.ts
  src/pages/LoginPage/index.tsx
Labels: 리팩토링

#30 REV-103/회원가입 페이지 구현
  src/apis/hooks/useEditProfile.ts
  src/assets/icons/eye-off.svg
  src/assets/icons/eye-on.svg
  src/assets/icons/index.ts
  src/assets/icons/logo-col.svg
  src/assets/images/index.ts
  src/assets/images/ranger-head.png
  src/assets/images/rangers.png
  src/components/Input/constants.ts
  src/components/Input/index.tsx
  src/components/PasswordInput/index.tsx
  src/components/index.ts
  src/pages/SignUpPage/hooks/constants.ts
  src/pages/SignUpPage/hooks/index.ts
  src/pages/SignUpPage/hooks/useEmailCheck.ts
  src/pages/SignUpPage/hooks/useNameCheck.ts
  src/pages/SignUpPage/hooks/usePasswordCheck.ts
  src/pages/SignUpPage/hooks/useSignUpCheck.ts
  src/pages/SignUpPage/index.tsx
  src/utils/authValidation.ts
  src/utils/constants.ts
  src/utils/index.ts
Labels: 리팩토링, 스타일, 기능

#31 REV-104/로그인 페이지 구현
  package-lock.json
  package.json
  src/components/Input/index.tsx
  src/mocks/handlers/login.ts
  src/pages/LoginPage/components/LoginGroup.tsx
  src/pages/LoginPage/components/LogoGroup.tsx
  src/pages/LoginPage/components/index.ts
  src/pages/LoginPage/index.tsx
  tailwind.config.js
Labels: 리팩토링, 스타일, 기능

#32 REV-113/메인 페이지 구현
  src/apis/hooks/index.ts
  src/apis/hooks/useGetAllReviews.ts
  src/apis/hooks/useGetCreatedReview.ts
  src/apis/hooks/useGetInvitedReview.ts
  src/apis/hooks/useGetReceivedReview.ts
  src/assets/icons/index.ts
  src/assets/icons/menu.svg
  src/assets/icons/plus.svg
  src/assets/images/index.ts
  src/assets/images/ranger-idle.png
  src/components/ReviewList/index.tsx
  src/components/index.ts
  src/mocks/handlers/dummyData.ts
  src/pages/MainPage/components/CreatedReviewItem/index.tsx
  src/pages/MainPage/components/InvitedReviewItem/index.tsx
  src/pages/MainPage/components/PageIntro/index.tsx
  src/pages/MainPage/components/ReceivedReviewItem/index.tsx
  src/pages/MainPage/components/ReviewList/index.tsx
  src/pages/MainPage/components/Tabs/index.tsx
  src/pages/MainPage/components/index.ts
  src/pages/MainPage/constants.ts
  src/pages/MainPage/index.tsx
  src/routes/Layout.tsx
  src/types/reviews.ts
  tailwind.config.js
Labels: 리팩토링, 스타일, 기능, 세팅

#35 REV-193/헤더 컴포넌트 구현
  src/assets/icons/arrow-left.svg
  src/assets/icons/basic-profile.svg
  src/assets/icons/index.ts
  src/assets/icons/logo-col.svg
  src/assets/icons/logo-row.svg
  src/assets/icons/logo-short.svg
  src/assets/images/ranger-head.png
  src/components/Header/index.tsx
  src/components/index.ts
  src/pages/LoginPage/index.tsx
  src/pages/MainPage/components/Tabs/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/SignUpPage/index.tsx
Labels: 기능

#34 REV-145/hook 네이밍 변경
  src/apis/hooks/index.ts
  src/apis/hooks/useCloseReview.ts
  src/apis/hooks/useCreateReview.ts
  src/apis/hooks/useDeleteReview.ts
  src/apis/hooks/useGetAllCreatedReview.ts
  src/apis/hooks/useGetAllInvitedReview.ts
  src/apis/hooks/useGetAllReceivedReview.ts
  src/apis/hooks/useGetAllResponseByReceiver.ts
  src/apis/hooks/useGetAllResponseByResponser.ts
  src/apis/hooks/useGetInvitedReview.ts
  src/apis/hooks/useGetReceivedReview.ts
  src/apis/hooks/useGetResponseByReceiver.ts
  src/apis/hooks/useGetResponseByResponser.ts
Labels: 리팩토링

#36 REV-196/유저 정보 관리
  src/apis/apiClient.ts
  src/apis/hooks/index.ts
  src/apis/hooks/useLogout.ts
  src/apis/hooks/useUser.ts
  src/components/Header/index.tsx
  src/constants/index.ts
  src/mocks/handlers/login.ts
  src/pages/LoginPage/index.tsx
Labels: 기능

#38 REV-152/마이 페이지 구현
  src/apis/hooks/index.ts
  src/apis/hooks/useEditName.ts
  src/apis/hooks/useEditPassword.ts
  src/apis/hooks/useEditProfile.ts
  src/assets/icons/check-in-the-circle.svg
  src/assets/icons/check.svg
  src/assets/icons/edit.svg
  src/assets/icons/index.ts
  src/assets/icons/left-sign-x.svg
  src/components/Input/index.tsx
  src/constants/index.ts
  src/hooks/index.ts
  src/hooks/useEmailCheck.ts
  src/hooks/useNameCheck.ts
  src/hooks/usePasswordCheck.ts
  src/mocks/handlers/profile.ts
  src/mocks/handlers/signUp.ts
  src/pages/LoginPage/components/LoginGroup.tsx
  src/pages/MyPage/components/ImageUpload/index.tsx
  src/pages/MyPage/components/index.ts
  src/pages/MyPage/hooks/index.ts
  src/pages/MyPage/hooks/useEditNameCheck.ts
  src/pages/MyPage/hooks/useEditPasswordCheck.ts
  src/pages/MyPage/index.tsx
  src/pages/SignUpPage/hooks/constants.ts
  src/pages/SignUpPage/hooks/index.ts
  src/pages/SignUpPage/hooks/useSignUpCheck.ts
  src/pages/SignUpPage/index.tsx
  src/utils/constants.ts
Labels: 스타일, 기능

#40 REV-149/결과 페이지 구현
  package-lock.json
  package.json
  src/apis/hooks/useGetReceivedReview.ts
  src/assets/icons/star.svg
  src/mocks/handlers/dummyData.ts
  src/mocks/handlers/main.ts
  src/pages/MainPage/components/PageIntro/index.tsx
  src/pages/MainPage/components/ReviewList/index.tsx
  src/pages/MainPage/components/Tabs/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/ReviewResultPage/components/DoughnutChart/index.tsx
  src/pages/ReviewResultPage/components/RadarChart/index.tsx
  src/pages/ReviewResultPage/components/StarChart/index.tsx
  src/pages/ReviewResultPage/components/index.ts
  src/pages/ReviewResultPage/index.tsx
  src/routes/Layout.tsx
  tailwind.config.js
Labels: 스타일, 기능

#37 REV-153/생성한 리뷰 단일 페이지 구현
  src/apis/hooks/index.ts
  src/apis/hooks/useGetAllResponseByReceiver.ts
  src/apis/hooks/useGetAllResponseByResponser.ts
  src/apis/hooks/useGetResponseByReceiver.ts
  src/apis/hooks/useGetResponseByResponser.ts
  src/apis/hooks/useGetReviewQuestion.ts
  src/assets/icons/index.ts
  src/assets/icons/no_result_alert.svg
  src/assets/icons/review-align.svg
  src/components/IconButton/index.tsx
  src/components/Profile/index.tsx
  src/components/SearchBar/index.tsx
  src/components/UserList/index.tsx
  src/mocks/handlers/manageHandler/index.ts
  src/mocks/handlers/manageHandler/mockData/index.ts
  src/pages/CreatedReviewManagePage/components/AllResponseReviewByReceiver.tsx
  src/pages/CreatedReviewManagePage/components/AllResponseReviewByResponser.tsx
  src/pages/CreatedReviewManagePage/components/NotFoundSearchUser.tsx
  src/pages/CreatedReviewManagePage/components/SortDropDown.tsx
  src/pages/CreatedReviewManagePage/components/Tabs.tsx
  src/pages/CreatedReviewManagePage/components/index.ts
  src/pages/CreatedReviewManagePage/constants.ts
  src/pages/CreatedReviewManagePage/index.tsx
  src/routes/constants.ts
  tailwind.config.js
Labels: 리팩토링, 스타일, 기능

#42 REV-206/라우터 리다이렉트 처리
  src/pages/ErrorPage/index.tsx
  src/pages/index.ts
  src/routes/loader.ts
  src/routes/router.tsx
Labels: 기능

#43 REV-255/다크모드 상태 관리 구현
  src/App.tsx
  src/components/ThemeProvider/index.tsx
  src/components/index.ts
  src/contexts/ThemeContext.tsx
  src/contexts/index.ts
  src/hooks/index.ts
  src/hooks/useDarkMode.ts
  src/pages/ReviewResultPage/components/DoughnutChart/index.tsx
  src/pages/ReviewResultPage/components/RadarChart/index.tsx
  src/routes/Layout.tsx
Labels: 리팩토링, 기능

#44 REV-254/별점 소수점 비율 구현
  src/mocks/handlers/dummyData.ts
  src/pages/ReviewResultPage/components/StarChart/constant.ts
  src/pages/ReviewResultPage/components/StarChart/index.tsx
Labels: 기능

#46 REV-151/리뷰 답변유형 페이지 구현
  src/apis/hooks/index.ts
  src/apis/hooks/useCreateResponse.ts
  src/apis/hooks/useGetReviewFirst.ts
  src/assets/icons/close.svg
  src/assets/icons/search.svg
  src/assets/icons/star.svg
  src/components/Header/index.tsx
  src/components/Profile/index.tsx
  src/components/SearchBar/index.tsx
  src/hooks/useStarRate/useStarRate.ts
  src/index.css
  src/mocks/handlers/dummyData.ts
  src/mocks/handlers/mainHandler/index.ts
  src/mocks/handlers/responseHandler/index.ts
  src/pages/ReviewReplyPage/components/Questions/index.tsx
  src/pages/ReviewReplyPage/components/ReceiverSelect/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyChoice/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyChoices/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyHexa/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyRating/StarRatingList/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyRating/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyText/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/index.ts
  src/pages/ReviewReplyPage/components/ReplyDropDown/index.tsx
  src/pages/ReviewReplyPage/components/ReplyHexagon/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReply/index.tsx
  src/pages/ReviewReplyPage/components/index.ts
  src/pages/ReviewReplyPage/index.tsx
  src/pages/ReviewReplyPage/types/index.ts
Labels: 리팩토링, 스타일, 기능

#45 REV-148/생성한 리뷰 관리 상세 페이지
  src/apis/hooks/index.ts
  src/apis/hooks/useCheckAllReceiverReceived.ts
  src/apis/hooks/useCloseReview.ts
  src/apis/hooks/useGetResponseByReceiver.ts
  src/apis/hooks/useGetResponseByResponser.ts
  src/apis/hooks/useGetReviewQuestion.ts
  src/apis/hooks/useSaveFinalResult.ts
  src/assets/icons/close-dropdown.svg
  src/assets/icons/filter-reply.svg
  src/assets/icons/index.ts
  src/components/IconButton/index.tsx
  src/components/StarRating/StarRatingList.tsx
  src/components/UserList/index.tsx
  src/constants/index.ts
  src/hooks/useStarRate/useStarRate.ts
  src/mocks/handlers/manageHandler/index.ts
  src/mocks/handlers/manageHandler/mockData/index.ts
  src/pages/CreatedReviewManagePage/components/AllResponseByReceiver/index.tsx
  src/pages/CreatedReviewManagePage/components/AllResponseByResponser/index.tsx
  src/pages/CreatedReviewManagePage/components/NotFoundSearchUser/index.tsx
  src/pages/CreatedReviewManagePage/components/ProfileGroup/index.tsx
  src/pages/CreatedReviewManagePage/components/QuestionGroup/index.tsx
  src/pages/CreatedReviewManagePage/components/ReviewDetail/index.tsx
  src/pages/CreatedReviewManagePage/components/SortDropDown/index.tsx
  src/pages/CreatedReviewManagePage/components/Tabs/index.tsx
  src/pages/CreatedReviewManagePage/components/index.ts
  src/pages/CreatedReviewManagePage/constants.ts
  src/pages/CreatedReviewManagePage/constants.tsx
  src/pages/CreatedReviewManagePage/hooks/index.ts
  src/pages/CreatedReviewManagePage/hooks/useResponseReviewByUser/index.ts
  src/pages/CreatedReviewManagePage/index.tsx
  src/pages/CreatedReviewManagePage/utils.ts
Labels: 리팩토링, 스타일, 기능

#48 REV-264/로그인 페이지 api 연결
  src/apis/apiClient.ts
  src/apis/hooks/useCreateReview.ts
  src/apis/hooks/useLogin.ts
  src/pages/LoginPage/index.tsx
Labels: 기능

#53 REV-263/회원가입 페이지 백엔드 api 연동
  src/apis/hooks/useSignUp.ts
  src/components/Input/index.tsx
  src/constants/index.ts
  src/pages/SignUpPage/hooks/index.ts
  src/pages/SignUpPage/hooks/useSignUpCheck.ts
  src/pages/SignUpPage/index.tsx
  src/utils/constants.ts
Labels: 리팩토링, 기능

#54 REV-267/마이페이지 백엔드 api 연동
  src/apis/hooks/useEditName.ts
  src/apis/hooks/useEditPassword.ts
  src/apis/hooks/useUser.ts
  src/pages/MyPage/hooks/useEditNameCheck.ts
  src/pages/MyPage/index.tsx
Labels: 리팩토링, 기능

#55 REV-203/토스트 컴포넌트 구현
  src/App.tsx
  src/assets/icons/close.svg
  src/components/Toast/ToastContainer/index.tsx
  src/components/Toast/ToastItem/index.tsx
  src/components/Toast/ToastProvider/index.tsx
  src/components/Toast/constants.ts
  src/components/Toast/index.ts
  src/components/Toast/types/index.ts
  src/components/index.ts
  src/contexts/ToastContext.tsx
  src/contexts/index.ts
  src/hooks/useToast.ts
  tailwind.config.js
Labels: 스타일, 기능, 세팅

#56 REV-310/회원가입 유효성 검사 수정
  src/utils/constants.ts
Labels: 리팩토링

#51 REV-281/메뉴 드롭다운 컴포넌트 구현
  src/components/Dropdown/Divider/index.tsx
  src/components/Dropdown/Item/index.tsx
  src/components/Dropdown/Menu/index.tsx
  src/components/Dropdown/Toggle/index.tsx
  src/components/Dropdown/index.tsx
  src/components/index.ts
Labels: 스타일, 기능

#57 REV-276/메인페이지 스타일 수정
  src/pages/MainPage/components/CreatedReviewItem/index.tsx
  src/pages/MainPage/components/InvitedReviewItem/index.tsx
  src/pages/MainPage/components/ReceivedReviewItem/index.tsx
  src/pages/MainPage/components/ReviewList/index.tsx
  src/pages/MainPage/components/Tabs/index.tsx
  src/pages/MainPage/index.tsx
  src/types/reviews.ts
Labels: 리팩토링, 스타일

#58 REV-258/생성한 리뷰 관리 페이지 api 연결
  src/apis/hooks/index.ts
  src/apis/hooks/useCheckAllReceiverReceived.ts
  src/apis/hooks/useCheckAllRecipientsReceived.ts
  src/apis/hooks/useCloseReview.ts
  src/apis/hooks/useGetAllResponseByReceiver.ts
  src/apis/hooks/useGetAllResponseByResponser.ts
  src/apis/hooks/useGetAllReviews.ts
  src/apis/hooks/useGetResponseByReceiver.ts
  src/apis/hooks/useGetReviewFirst.ts
  src/apis/hooks/useGetReviewQuestion.ts
  src/apis/hooks/useSaveFinalResult.ts
  src/apis/hooks/useSendReview.ts
  src/apis/hooks/useUser.ts
  src/components/Header/index.tsx
  src/components/Toast/ToastItem/index.tsx
  src/components/UserList/index.tsx
  src/mocks/handlers/loginHandler/index.ts
  src/mocks/handlers/profileHandler/index.ts
  src/mocks/handlers/responseHandler/index.ts
  src/mocks/handlers/signUpHandler/index.ts
  src/pages/CreatedReviewManagePage/components/AllResponseByReceiver/index.tsx
  src/pages/CreatedReviewManagePage/components/AllResponseByResponser/index.tsx
  src/pages/CreatedReviewManagePage/components/QuestionGroup/index.tsx
  src/pages/CreatedReviewManagePage/components/ReviewDetail/index.tsx
  src/pages/CreatedReviewManagePage/components/Tabs/index.tsx
  src/pages/CreatedReviewManagePage/constants.tsx
  src/pages/CreatedReviewManagePage/hooks/useResponseReviewByUser/index.ts
  src/pages/CreatedReviewManagePage/index.tsx
  src/pages/CreatedReviewManagePage/utils.ts
  src/pages/LoginPage/index.tsx
  src/pages/MainPage/components/CreatedReviewItem/index.tsx
  src/pages/MainPage/components/InvitedReviewItem/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/ReviewCreatePage/components/QuestionItem/index.tsx
  src/pages/ReviewReplyPage/components/ReceiverSelect/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReply/index.tsx
  src/pages/ReviewReplyPage/index.tsx
  src/routes/router.tsx
  src/types/reviews.ts
Labels: 기능

#59 REV-309/useUser 로직 수정
  src/apis/hooks/useLogin.ts
  src/apis/hooks/useLogout.ts
  src/apis/hooks/useUser.ts
  src/components/Dropdown/Item/index.tsx
  src/components/Dropdown/Menu/index.tsx
  src/components/Header/index.tsx
  src/pages/LoginPage/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/ReviewReplyPage/components/ReceiverSelect/index.tsx
Labels: 리팩토링, 기능

#61 REV-313/메인페이지 무한스크롤 구현
  src/apis/hooks/index.ts
  src/apis/hooks/useGetCreatedReviews.ts
  src/apis/hooks/useGetInvitedReviews.ts
  src/apis/hooks/useGetReceivedReviews.ts
  src/components/Header/index.tsx
  src/hooks/index.ts
  src/hooks/useInfiniteScroll.ts
  src/pages/MainPage/components/CreatedReviewList/CreatedReviewItem.tsx
  src/pages/MainPage/components/CreatedReviewList/index.tsx
  src/pages/MainPage/components/InvitedReviewList/InvitedReviewItem.tsx
  src/pages/MainPage/components/InvitedReviewList/index.tsx
  src/pages/MainPage/components/ReceivedReviewList/ReceivedReviewItem.tsx
  src/pages/MainPage/components/ReceivedReviewList/index.tsx
  src/pages/MainPage/components/ReviewList/index.tsx
  src/pages/MainPage/components/index.ts
  src/pages/MainPage/index.tsx
  src/utils/index.ts
  src/utils/scrollToTop.ts
Labels: 리팩토링, 기능

#64 REV-318/리뷰 생성 페이지 스타일 수정
  src/components/Header/index.tsx
  src/components/SearchBar/index.tsx
  src/hooks/index.ts
  src/pages/ReviewCreatePage/components/QuestionItem/index.tsx
  src/pages/ReviewCreatePage/components/ResponserSelect/ResponserList.tsx
  src/pages/ReviewCreatePage/components/ResponserSelect/index.tsx
  src/pages/ReviewCreatePage/components/ReviewQuestionAdder/index.tsx
  src/pages/ReviewCreatePage/index.tsx
  src/pages/ReviewCreatePage/types/index.ts
Labels: 리팩토링, 스타일, 기능

#68 REV-305/스크롤바 스타일 추가
  src/index.css
Labels: 스타일

#67 REV-316/작성자별 유저 리스트 컴포넌트
  src/apis/hooks/index.ts
  src/apis/hooks/useGetAllResponseByReceiver.ts
  src/apis/hooks/useGetResponseByReceiver.ts
  src/apis/hooks/useGetResponseByResponser.ts
  src/apis/hooks/useSaveFinalResult.ts
  src/apis/hooks/useUpdateFinalReviewAnswer.ts
  src/components/Header/index.tsx
  src/components/UserList/index.tsx
  src/pages/CreatedReviewManagePage/components/AllResponseByReceiver/index.tsx
  src/pages/CreatedReviewManagePage/components/AllResponseByResponser/index.tsx
  src/pages/CreatedReviewManagePage/components/AnswerGroup/index.tsx
  src/pages/CreatedReviewManagePage/components/ProfileGroup/index.tsx
  src/pages/CreatedReviewManagePage/components/ReceiverTabReviewDatail/index.tsx
  src/pages/CreatedReviewManagePage/components/ResponserTabReviewDetail/index.tsx
  src/pages/CreatedReviewManagePage/components/SelectResponseUser/index.tsx
  src/pages/CreatedReviewManagePage/components/index.ts
  src/pages/CreatedReviewManagePage/constants.tsx
  src/pages/CreatedReviewManagePage/index.tsx
  src/pages/CreatedReviewManagePage/utils.ts
Labels: 기능

#69 REV-273/404 페이지 마크업
  src/assets/images/error-white.png
  src/assets/images/error.png
  src/assets/images/index.ts
  src/assets/images/sans-dark.png
  src/assets/images/sans-light.png
  src/pages/ErrorPage/index.tsx
Labels: 스타일

#66 REV-307/답변 페이지 케이스별 분기처리
  src/apis/hooks/index.ts
  src/apis/hooks/useEditResponse.ts
  src/apis/hooks/useGetResponseByResponserForReviewReplyPage.ts
  src/pages/MainPage/components/InvitedReviewList/InvitedReviewItem.tsx
  src/pages/MainPage/components/InvitedReviewList/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/ReviewReplyPage/components/Questions/index.tsx
  src/pages/ReviewReplyPage/components/ReceiverSelect/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyChoice/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyChoices/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyDropdown/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyHexa/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyRating/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyText/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReply/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEdit/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/index.tsx
  src/pages/ReviewReplyPage/components/index.ts
  src/pages/ReviewReplyPage/index.tsx
  src/pages/ReviewReplyPage/types/index.ts
  src/pages/ReviewReplyPage/types/reviewReplyEdit.ts
  src/pages/ReviewReplyPage/types/reviewReplyStart.ts
Labels: 리팩토링, 기능

#70 REV-204/메인, 결과 페이지 스켈레톤 구현
  src/components/Header/index.tsx
  src/pages/MainPage/components/CreatedReviewList/index.tsx
  src/pages/MainPage/components/InvitedReviewList/index.tsx
  src/pages/MainPage/components/ListSkeleton/index.tsx
  src/pages/MainPage/components/ReceivedReviewList/index.tsx
  src/pages/MainPage/components/index.ts
  src/pages/MainPage/index.tsx
  src/pages/ReviewResultPage/components/ResultSkeleton/index.tsx
  src/pages/ReviewResultPage/components/index.ts
  src/pages/ReviewResultPage/index.tsx
  src/routes/router.tsx
  tailwind.config.js
Labels: 스타일, 기능, 세팅

#74 REV-338/모달 컴포넌트 구현
  src/components/Modal/index.tsx
  src/components/index.ts
Labels: 스타일, 기능

#75 REV-270/리뷰 결과 페이지 백엔드 api 연동
  src/pages/ReviewResultPage/index.tsx
Labels: 스타일

#76 REV-354/리뷰 상세 조회 api 분리
  src/apis/hooks/index.ts
  src/apis/hooks/useGetReviewForCreator.ts
  src/apis/hooks/useGetReviewForParticipation.ts
  src/pages/ReviewReplyPage/components/QuestionItem/index.tsx
  src/pages/ReviewReplyPage/components/Questions/index.tsx
  src/pages/ReviewReplyPage/components/ReceiverItem/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyChoice/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyChoices/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyDropdown/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyHexa/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEdit/ReviewReply.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEdit/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEnd/ReviewReply.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEnd/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/ReviewReply.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/ReviewSelect.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/index.tsx
  src/pages/ReviewReplyPage/hooks/useClickNextButton.ts
  src/pages/ReviewReplyPage/hooks/useHandleQuestion.ts
  src/pages/ReviewReplyPage/hooks/useHandleReceiver.ts
  src/pages/ReviewReplyPage/hooks/useReplyComplete.ts
Labels: 리팩토링

#77 REV-365/모달, 드롭다운 컴포넌트 긴급 수정
  src/components/Dropdown/Item/index.tsx
  src/components/Dropdown/Menu/index.tsx
  src/components/Header/index.tsx
  src/components/Modal/index.tsx
Labels: 긴급, 리팩토링

#79 REV-367/답변 페이지 api 긴급 수정
  src/apis/hooks/index.ts
  src/apis/hooks/useGetResponseByResponserForCreator.ts
  src/apis/hooks/useGetResponseByResponserForParticipation.ts
  src/apis/hooks/useGetReviewForCreator.ts
  src/apis/hooks/useGetReviewForParticipation.ts
  src/pages/CreatedReviewManagePage/components/ResponserTabReviewDetail/index.tsx
  src/pages/ReviewReplyPage/components/QuestionItem/index.tsx
  src/pages/ReviewReplyPage/components/Questions/index.tsx
  src/pages/ReviewReplyPage/components/ReceiverItem/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyChoice/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyChoices/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyDropdown/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyHexa/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEdit/ReviewReply.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEdit/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEnd/ReviewReply.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEnd/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/ReviewReply.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/ReviewSelect.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/index.tsx
  src/pages/ReviewReplyPage/hooks/useClickNextButton.ts
  src/pages/ReviewReplyPage/hooks/useHandleQuestion.ts
  src/pages/ReviewReplyPage/hooks/useHandleReceiver.ts
  src/pages/ReviewReplyPage/hooks/useReplyComplete.ts
  src/types/index.ts
  src/types/reviewDetailed.ts
Labels: 긴급, 리팩토링

#78 REV-349/리뷰 삭제 기능 추가
  src/apis/hooks/index.ts
  src/apis/hooks/useDeleteReview.ts
  src/apis/hooks/useGetAllReviews.ts
  src/components/Dropdown/Toggle/index.tsx
  src/pages/MainPage/components/CreatedReviewList/CreatedReviewItem.tsx
  src/pages/MainPage/components/CreatedReviewList/index.tsx
  src/pages/MainPage/components/InvitedReviewList/InvitedReviewItem.tsx
  src/pages/MainPage/components/InvitedReviewList/index.tsx
  src/pages/MainPage/components/ReceivedReviewList/ReceivedReviewItem.tsx
  src/pages/MainPage/components/ReceivedReviewList/index.tsx
  src/pages/MainPage/index.tsx
Labels: 기능

#80 REV-260/에러 바운더리 처리
  package-lock.json
  package.json
  src/App.tsx
  src/apis/hooks/index.ts
  src/apis/hooks/useGetCreatedReviews.ts
  src/apis/hooks/useGetInvitedReviews.ts
  src/apis/hooks/useGetReceivedReviews.ts
  src/apis/hooks/useLogin.ts
  src/apis/hooks/useLogout.ts
  src/apis/hooks/useUser.ts
  src/components/ErrorBoundaries/ApiErrorBoundary/index.tsx
  src/components/ErrorBoundaries/TokenErrorBoundary/index.tsx
  src/components/ErrorBoundaries/index.ts
  src/components/index.ts
  src/pages/ErrorPage/index.tsx
  src/pages/MainPage/index.tsx
  src/routes/Layout.tsx
  src/routes/router.tsx
Labels: 버그, 기능

#81 REV-350/리뷰 마감, 종료 시 미응답 접근 불가 처리
  src/pages/MainPage/index.tsx
Labels: 기능

#82 REV-348/모달 적용
  src/pages/MyPage/hooks/useEditNameCheck.ts
  src/pages/MyPage/hooks/useEditPasswordCheck.ts
  src/pages/MyPage/index.tsx
  src/pages/ReviewReplyPage/components/ReceiverItem/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyDropdown/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEdit/ReviewReply.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEdit/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEnd/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/ReviewReply.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/index.tsx
Labels: 리팩토링, 기능

#83 REV-293/프로필 이미지 업로드 기능 구현
  src/apis/hooks/index.ts
  src/apis/hooks/useEditImage.ts
  src/apis/hooks/useEditName.ts
  src/apis/hooks/useEditPassword.ts
  src/apis/hooks/useUser.ts
  src/assets/icons/image.svg
  src/assets/icons/index.ts
  src/components/Header/index.tsx
  src/pages/MyPage/index.tsx
Labels: 스타일, 기능

#71 REV-329/설문 마감, 전송 api 연결
  src/apis/hooks/index.ts
  src/apis/hooks/useCheckAllReceiverReceived.ts
  src/apis/hooks/useCheckAllRecipientsReceived.ts
  src/apis/hooks/useCloseReview.ts
  src/apis/hooks/useGetInvitedReview.ts
  src/apis/hooks/useGetResponseByReceiver.ts
  src/apis/hooks/useGetResponseByResponser.ts
  src/apis/hooks/useLogin.ts
  src/apis/hooks/useSaveFinalResult.ts
  src/apis/hooks/useSendReview.ts
  src/apis/hooks/useUpdateFinalReviewAnswer.ts
  src/pages/CreatedReviewManagePage/components/ReceiverTabReviewDatail/index.tsx
  src/pages/CreatedReviewManagePage/components/ResponserTabReviewDetail/index.tsx
  src/pages/CreatedReviewManagePage/components/Tabs/index.tsx
  src/pages/CreatedReviewManagePage/index.tsx
  src/pages/CreatedReviewManagePage/utils.ts
Labels: 기능

#84 REV-368/답변 페이지 육각형 스탯 수정
  src/pages/ReviewReplyPage/components/Questions/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyHexa/index.tsx
  src/pages/ReviewReplyPage/hooks/useHandleQuestion.ts
Labels: 리팩토링, 버그

#85 REV-369/답변 페이지 수정 및 종료 시, 모달 에러 고치기
  src/pages/ReviewReplyPage/components/ReviewReplyEdit/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEnd/index.tsx
Labels: 긴급, 버그

#87 REV-372/준비중 토스트 구현
  src/components/Header/index.tsx
  src/components/Toast/constants.ts
  src/components/Toast/types/index.ts
  src/contexts/ToastContext.tsx
  src/pages/ReviewCreatePage/components/ReviewQuestionAdder/index.tsx
  src/pages/ReviewResultPage/index.tsx
  tailwind.config.js
Labels: 스타일, 기능

#90 REV-371/테스트 전 피드백반영
  src/apis/hooks/useSaveFinalResult.ts
  src/apis/hooks/useSendReview.ts
  src/pages/CreatedReviewManagePage/components/AnswerGroup/index.tsx
  src/pages/CreatedReviewManagePage/components/ReceiverTabReviewDatail/index.tsx
  src/pages/CreatedReviewManagePage/components/ResponserTabReviewDetail/index.tsx
  src/pages/CreatedReviewManagePage/index.tsx
  src/pages/LoginPage/components/LoginGroup.tsx
  src/pages/LoginPage/index.tsx
Labels: 기능

#91 REV-370/답변 페이지 리펙토링
  src/assets/icons/index.ts
  src/components/Profile/index.tsx
  src/pages/CreatedReviewManagePage/constants.tsx
  src/pages/ReviewCreatePage/components/QuestionItem/constants.tsx
  src/pages/ReviewCreatePage/components/QuestionTypeModal/constants.tsx
  src/pages/ReviewReplyPage/components/QuestionItem/index.tsx
  src/pages/ReviewReplyPage/components/Questions/index.tsx
  src/pages/ReviewReplyPage/components/ReceiverItem/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyChoice/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyChoices/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyDropdown/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyHexa/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyRating/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyText/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEdit/ReviewReply.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEdit/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEnd/ReviewReply.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/ReviewReply.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/index.tsx
Labels: 리팩토링, 버그, 스타일, 기능

#86 REV-351/정제 api 연동
  package-lock.json
  package.json
  src/assets/icons/index.ts
  src/assets/icons/save.svg
  src/hooks/index.ts
  src/hooks/useRefine.ts
  src/pages/CreatedReviewManagePage/components/AnswerGroup/RenderRefinedSubjective.tsx
  src/pages/CreatedReviewManagePage/components/AnswerGroup/index.tsx
Labels: 긴급, 리팩토링, 스타일, 기능, 세팅

#93 REV-381/최종 리뷰 결과 반영 안되는 문제 해결
  src/components/UserList/index.tsx
  src/pages/CreatedReviewManagePage/components/AllResponseByReceiver/index.tsx
  src/pages/CreatedReviewManagePage/index.tsx
Labels: 긴급, 버그

#95 REV-382/답변 페이지 수신자 선택 드롭다운 스타일 수정
  src/components/Header/index.tsx
  src/components/Profile/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/ReviewSelect.tsx
Labels: 리팩토링, 스타일

#96 REV-379/스타일 긴급 수정
  src/assets/icons/alert.svg
  src/assets/icons/edit.svg
  src/assets/icons/image.svg
  src/assets/icons/index.ts
  src/components/Header/index.tsx
  src/components/UserList/index.tsx
  src/pages/CreatedReviewManagePage/components/AnswerGroup/RenderRefinedSubjective.tsx
  src/pages/CreatedReviewManagePage/components/AnswerGroup/index.tsx
  src/pages/CreatedReviewManagePage/components/NotFoundSearchUser/index.tsx
  src/pages/CreatedReviewManagePage/components/ReceiverTabReviewDatail/index.tsx
  src/pages/CreatedReviewManagePage/components/ResponserTabReviewDetail/index.tsx
  src/pages/CreatedReviewManagePage/components/SortDropDown/index.tsx
  src/pages/MainPage/components/EmptyReview/index.tsx
  src/pages/MainPage/components/InvitedReviewList/index.tsx
  src/pages/MainPage/components/ReceivedReviewList/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/ReviewCreatePage/components/QuestionItem/index.tsx
  src/pages/ReviewReplyPage/components/QuestionItem/index.tsx
  src/pages/ReviewReplyPage/components/ReceiverItem/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyChoice/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyChoices/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyDropdown/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyRating/StarRatingList/index.tsx
Labels: 스타일

#97 REV-383/육각형 스탯 결과 취합
  src/pages/ReviewResultPage/components/RadarChart/index.tsx
Labels: 기능

#98 REV-384/답변 페이지 뒤로가기 기능 추가
  src/pages/ReviewReplyPage/components/ReviewReplyEdit/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEnd/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/index.tsx
  src/pages/ReviewReplyPage/index.tsx
Labels: 기능
