Repository prgrms-web-devcourse/Team-12-ReviewRanger-FE, pull requests merged in 2023-12, with the labels that each got.

#99 REV-387/답변 페이지 수신자 선택 스타일 수정
  src/components/Modal/index.tsx
  src/components/Profile/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEdit/ReviewReply.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEdit/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEnd/ReviewReply.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/ReceiverList.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/ReceiverSelect.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/ReviewReply.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/ReviewSelect.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/index.tsx
  src/pages/ReviewReplyPage/types/index.ts
  src/pages/ReviewReplyPage/types/reviewReplyStart.ts
Labels: 리팩토링, 스타일, 기능

#100 REV-386/취합된 주관식 답변 저장 api 연결
  src/apis/hooks/useUpdateFinalReviewAnswer.ts
  src/hooks/useRefine.ts
  src/pages/CreatedReviewManagePage/components/AnswerGroup/RenderHexaStat.tsx
  src/pages/CreatedReviewManagePage/components/AnswerGroup/RenderRefinedSubjective.tsx
  src/pages/CreatedReviewManagePage/components/AnswerGroup/RenderStarRatingAnswer.tsx
  src/pages/CreatedReviewManagePage/components/AnswerGroup/RenderSubjectiveAnswer.tsx
  src/pages/CreatedReviewManagePage/components/AnswerGroup/index.tsx
  src/pages/CreatedReviewManagePage/components/ReceiverTabReviewDatail/index.tsx
  src/pages/CreatedReviewManagePage/components/ResponserTabReviewDetail/index.tsx
  src/types/reviewDetailed.ts
Labels: 리팩토링, 기능

#102 REV-392/답변 페이지 디자인 수정
  src/pages/ReviewReplyPage/components/QuestionItem/index.tsx
  src/pages/ReviewReplyPage/components/Questions/index.tsx
  src/pages/ReviewReplyPage/components/ReceiverItem/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyHexa/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyText/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEdit/ReviewReply.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEdit/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEnd/ReviewReply.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEnd/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/ReceiverList.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/ReceiverSelect.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/ReviewReply.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/index.tsx
  tailwind.config.js
Labels: 리팩토링, 세팅

#104 REV-398/도넛 차트 라벨 텍스트 수정
  src/pages/ReviewResultPage/components/DoughnutChart/index.tsx
Labels: 스타일

#108 REV-400/회원가입 페이지 디자인 수정
  src/apis/hooks/useSignUp.ts
  src/components/Input/index.tsx
  src/pages/SignUpPage/index.tsx
Labels: 버그, 스타일

#109 REV-396/생성한 리뷰 관리 디자인 수정
  src/pages/CreatedReviewManagePage/components/AnswerGroup/RenderHexaStat.tsx
  src/pages/CreatedReviewManagePage/components/ReceiverTabReviewDatail/index.tsx
  src/pages/CreatedReviewManagePage/components/ResponserTabReviewDetail/index.tsx
  src/pages/CreatedReviewManagePage/index.tsx
Labels: 리팩토링, 스타일

#111 REV-403/헤더 뒤로가기 방지 기능 리팩토링
  src/components/Header/index.tsx
  src/hooks/index.ts
  src/hooks/useCheckHeaderRoute.ts
  src/pages/ReviewReplyPage/components/ReviewReplyStart/ReceiverSelect.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/index.tsx
Labels: 리팩토링, 스타일

#113 REV-396/생성한 리뷰 관리 디자인 수정
  src/assets/icons/index.ts
  src/assets/icons/text.svg
  src/components/UserList/index.tsx
  src/pages/CreatedReviewManagePage/components/AllResponseByReceiver/index.tsx
  src/pages/CreatedReviewManagePage/components/AllResponseByResponser/index.tsx
  src/pages/CreatedReviewManagePage/components/AnswerGroup/RenderHexaStat.tsx
  src/pages/CreatedReviewManagePage/components/AnswerGroup/RenderRefinedSubjective.tsx
  src/pages/CreatedReviewManagePage/components/AnswerGroup/RenderStarRatingAnswer.tsx
  src/pages/CreatedReviewManagePage/components/AnswerGroup/RenderSubjectiveAnswer.tsx
  src/pages/CreatedReviewManagePage/components/AnswerGroup/index.tsx
  src/pages/CreatedReviewManagePage/components/ProfileGroup/index.tsx
  src/pages/CreatedReviewManagePage/components/ReceiverTabReviewDatail/index.tsx
  src/pages/CreatedReviewManagePage/components/ResponserTabReviewDetail/index.tsx
  src/pages/CreatedReviewManagePage/components/SortDropDown/index.tsx
  src/pages/CreatedReviewManagePage/constants.tsx
  src/pages/CreatedReviewManagePage/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyDropdown/index.tsx
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyText/index.tsx
Labels: 스타일

#114 REV-402/수신자 클릭시 1번 질문으로 이동
  src/pages/ReviewReplyPage/components/ReplyCategory/ReplyRating/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEdit/ReviewReply.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEnd/ReviewReply.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/ReviewReply.tsx
Labels: 리팩토링

#115 REV-405/답변 페이지 수신자 이미지 적용
  src/apis/hooks/useGetResponseByResponserForParticipation.ts
  src/components/PersonalAnswer/index.tsx
  src/components/Profile/index.tsx
  src/pages/ReviewReplyPage/components/ReceiverItem/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEdit/ReviewReply.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEdit/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyEnd/index.tsx
  src/pages/ReviewReplyPage/components/ReviewReplyStart/ReceiverList.tsx
  src/pages/ReviewReplyPage/hooks/useReplyComplete.ts
  src/pages/ReviewReplyPage/types/reviewReplyEdit.ts
  src/pages/ReviewReplyPage/types/reviewReplyEnd.ts
  src/pages/ReviewReplyPage/types/reviewReplyStart.ts
  src/types/reviewDetailed.ts
Labels: 기능
